baseURL = "https://www.theresonauts.com/"
languageCode = "en"
defaultContentLanguage = "en"

#title = "The Resonauts"
copyright = "© 2025 The Resonauts"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "The Resonauts"
  headline = "Welcome earthlings! 🚀🎶"
  image = "logo.jpg"

  links = [
    { instagram = "https://www.instagram.com/p/DPeSYrlEWN6/" },
    { youtube = "https://www.youtube.com/watch?v=IFcmzGC4_LI&list=PL_ap4VSfJBuIruTgDoMj_03Wogp8KORnb&index=2" },
    { press-photos = {href = "https://www.flickr.com/photos/203113095@N04/", text = "Press Photos"} },
    { facebook = "https://www.facebook.com/people/The-Resonauts/61577069911906/" },
    { email = "mailto:resonautsbooking@gmail.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

[caches]
  [caches.images]
    dir = ':cacheDir/images'